name: record_linux
description: Linux specific implementation for record package (patched for record_platform_interface 1.6.0).
version: 0.7.3
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ">=1.0.2 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
